"""Agentic RAG utilities shared across course modules."""

import json
import os
from dataclasses import dataclass
from typing import Any, Literal, TypeAlias, cast

from openai import OpenAI
from openai.types.responses import ResponseInputParam, ToolParam

from .llm import call_llm
from .search import SearchTool
from .types import Document


ToolDefinition: TypeAlias = ToolParam
Message: TypeAlias = dict[str, Any]
MessageHistory: TypeAlias = list[Any]
RAGMode: TypeAlias = Literal["agentic", "simple"]

DEFAULT_OPENAI_MODEL = os.getenv("OPENAI_MODEL_NAME", "gpt-5.4-mini")


SEARCH_TOOL_DEFINITION: ToolDefinition = {
    "type": "function",
    "name": "search",
    "description": "Search the document database for entries matching the given query.",
    "parameters": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "Search query text to look up in the indexed documents."
            }
        },
        "required": ["query"],
        "additionalProperties": False
    },
    "strict": True,
}

@dataclass
class UsageCostConfig:
    input_price_per_million: float = 0.75
    output_price_per_million: float = 4.50


@dataclass
class AgentRunStats:
    cost_in_dollars: float = 0.0
    tool_calls: int = 0


class AgenticRAG[TDocument: Document]:
    """Retrieval-augmented answer generator with simple and agentic modes."""

    def __init__(
            self,
            llm_client: OpenAI,
            search_tool: SearchTool[TDocument],
            instructions: str,
            model: str = DEFAULT_OPENAI_MODEL,
            max_turns: int = 10,
            mode: RAGMode = "agentic",
            usage_cost_config: UsageCostConfig | None = None,
            ) -> None:
        if mode not in ("agentic", "simple"):
            raise ValueError("mode must be either 'agentic' or 'simple'.")

        self.llm_client = llm_client
        self.search_tool = search_tool
        self.instructions = instructions
        self.model = model
        self.max_turns = max_turns
        self.mode = mode
        self.usage_cost_config = usage_cost_config or UsageCostConfig()
        self.last_message_history: MessageHistory = []
        self.last_run_stats = AgentRunStats()
        self._total_cost = 0.0

    def _calculate_response_cost(self, response: Any) -> float:
        usage = getattr(response, "usage", None)

        if usage is None:
            return 0.0

        input_tokens = getattr(usage, "input_tokens", 0)
        output_tokens = getattr(usage, "output_tokens", 0)

        input_price = self.usage_cost_config.input_price_per_million / 1_000_000
        output_price = self.usage_cost_config.output_price_per_million / 1_000_000

        return input_tokens * input_price + output_tokens * output_price

    def total_cost(self) -> float:
        """Return the cumulative cost for answers generated by this RAG."""
        return round(self._total_cost, 6)

    def reset(self) -> None:
        """Clear cumulative usage and latest-run metadata."""
        self._total_cost = 0.0
        self.last_message_history = []
        self.last_run_stats = AgentRunStats()

    def _search_and_serialize(self, call: Any) -> Message:
        args = json.loads(call.arguments)

        if call.name != "search":
            raise ValueError(f"Unsupported tool call: {call.name}")

        result = self.search_tool.search(**args)

        return {
            "type": "function_call_output",
            "call_id": call.call_id,
            "output": json.dumps(result, indent=2),
        }

    def _use_tools_until_done(
            self,
            message_history: MessageHistory,
            ) -> tuple[str, MessageHistory, AgentRunStats]:
        run_stats = AgentRunStats()

        for _ in range(self.max_turns):
            response = call_llm(
                client=self.llm_client,
                messages=cast(ResponseInputParam, message_history),
                model=self.model,
                tools=[SEARCH_TOOL_DEFINITION],
            )
            run_stats.cost_in_dollars += self._calculate_response_cost(response)

            message_history = [*message_history, *response.output]

            function_calls = [
                item for item in response.output
                if item.type == "function_call"
            ]

            if function_calls:
                run_stats.tool_calls += len(function_calls)
                function_results = [
                    self._search_and_serialize(call)
                    for call in function_calls
                ]
                message_history = [*message_history, *function_results]
                continue

            if response.output_text:
                run_stats.cost_in_dollars = round(run_stats.cost_in_dollars, 6)
                return response.output_text, message_history, run_stats

            raise RuntimeError(
                "The LLM response did not include a final answer or tool call."
            )

        raise RuntimeError(f"Agent stopped after {self.max_turns} turns.")

    def _answer_with_single_search(
        self,
        question: str,
    ) -> tuple[str, MessageHistory, AgentRunStats]:
        documents = self.search_tool.search(question)
        serialized_documents = json.dumps(documents, indent=2)
        message_history: MessageHistory = [
            {
                "role": "system",
                "content": self.instructions,
            },
            {
                "role": "user",
                "content": (
                    f"Question: {question}\n\n"
                    "Context:\n"
                    f"{serialized_documents}"
                ),
            },
        ]

        response = call_llm(
            client=self.llm_client,
            messages=cast(ResponseInputParam, message_history),
            model=self.model,
        )
        run_stats = AgentRunStats(
            cost_in_dollars=round(self._calculate_response_cost(response), 6),
            tool_calls=0,
        )
        message_history = [*message_history, *response.output]

        if response.output_text:
            return response.output_text, message_history, run_stats

        raise RuntimeError("The LLM response did not include a final answer.")

    def _answer_agentically(
            self,
            question: str,
            ) -> tuple[str, MessageHistory, AgentRunStats]:
        message_history: MessageHistory = [
            {
                "role": "system",
                "content": self.instructions,
            },
            {
                "role": "user",
                "content": question,
            },
        ]

        return self._use_tools_until_done(message_history)

    def find_and_reply(self, question: str) -> str:
        if self.mode == "simple":
            answer, message_history, run_stats = self._answer_with_single_search(
                question
            )
        else:
            answer, message_history, run_stats = self._answer_agentically(question)

        self.last_message_history = message_history
        self.last_run_stats = run_stats
        self._total_cost += run_stats.cost_in_dollars

        return answer
