[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true
workspace_id = "aa93cb4e-b9f6-45b2-880c-0e1117407e87"
organization_id = "15c7193d-b628-473a-a056-16fb19ca15a3"

[sources.filesystem]
bucket_url = "file:///C:/Users/JoanPareja/.claude/projects"

[sources.agent_traces_source]
base_url = "https://test-agent-traces-api-xt2e7ottma-ew.a.run.app"

[workspace.settings]
name = "playground"
